package talosconfig

import (
	"strings"
	"testing"
)

const sampleConfig = `# generated by CABPT
version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: abc.def
  install:
    disk: DISK_ID
    diskSelector:
      size: '>= 500GB'
      type: nvme
    image: factory.talos.dev/metal-installer/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef:v1.14.1
    extraKernelArgs:
      - talos.logging.kernel=udp://10.0.0.5:514/
  network:
    hostname: node1
    nameservers:
      - 10.0.0.2
  time:
    servers:
      - time.cloudflare.com
cluster:
  clusterName: demo
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: ignored
`

func TestParseReadsInstallNetworkAndTime(t *testing.T) {
	cfg, err := Parse(sampleConfig)
	if err != nil {
		t.Fatalf("Parse() error: %v", err)
	}
	if !cfg.Found {
		t.Fatal("Found must be true for a v1alpha1 machine document")
	}
	if cfg.Install.Disk != "DISK_ID" {
		t.Errorf("Install.Disk = %q", cfg.Install.Disk)
	}
	if !strings.Contains(string(cfg.Install.DiskSelector), "size: '>= 500GB'") || !strings.Contains(string(cfg.Install.DiskSelector), "type: nvme") {
		t.Errorf("Install.DiskSelector = %q", cfg.Install.DiskSelector)
	}
	if cfg.ImageTag() != "v1.14.1" {
		t.Errorf("ImageTag() = %q", cfg.ImageTag())
	}
	if len(cfg.Install.ExtraKernelArgs) != 1 || cfg.Install.ExtraKernelArgs[0] != "talos.logging.kernel=udp://10.0.0.5:514/" {
		t.Errorf("ExtraKernelArgs = %q", cfg.Install.ExtraKernelArgs)
	}
	if cfg.Network.Hostname != "node1" || len(cfg.Network.Nameservers) != 1 || cfg.Network.Nameservers[0] != "10.0.0.2" {
		t.Errorf("Network = %+v", cfg.Network)
	}
	if len(cfg.Time.Servers) != 1 || cfg.Time.Servers[0] != "time.cloudflare.com" {
		t.Errorf("Time = %+v", cfg.Time)
	}
	if cfg.InstallDiskPath() != "" {
		t.Errorf("DISK_ID placeholder must not be a disk path, got %q", cfg.InstallDiskPath())
	}
}

func TestParseBlankIsNoConfig(t *testing.T) {
	cfg, err := Parse("  \n")
	if err != nil || cfg != nil {
		t.Fatalf("Parse(blank) = %+v, %v; want nil, nil", cfg, err)
	}
}

func TestParseRejectsInvalidYAML(t *testing.T) {
	if _, err := Parse("machine: [unclosed"); err == nil {
		t.Fatal("expected an error for invalid YAML")
	}
}

func TestParseWithoutV1alpha1DocumentIsEmpty(t *testing.T) {
	cfg, err := Parse("apiVersion: v1alpha1\nkind: HostnameConfig\nhostname: x\n")
	if err != nil {
		t.Fatal(err)
	}
	if cfg == nil || cfg.Found || cfg.Install.Image != "" || cfg.Network.Hostname != "" {
		t.Fatalf("expected an empty config with Found false, got %+v", cfg)
	}
}

func TestInstallDiskPathAndImageTag(t *testing.T) {
	tests := []struct {
		disk, image, wantPath, wantTag string
	}{
		{"/dev/sda", "ghcr.io/siderolabs/installer:v1.14.0", "/dev/sda", "v1.14.0"},
		{"/dev/disk/by-id/nvme-X", "factory.talos.dev/metal-installer/abc:v1.14", "/dev/disk/by-id/nvme-X", "v1.14"},
		{"DISK_ID", "registry:5000/installer:v1.14.2-alpha.1", "", "v1.14.2-alpha.1"},
		{"", "ghcr.io/siderolabs/installer:latest", "", ""},
		{"", "ghcr.io/siderolabs/installer@sha256:abcd", "", ""},
		{"", "", "", ""},
	}
	for _, tt := range tests {
		cfg := &Config{Install: Install{Disk: tt.disk, Image: tt.image}}
		if got := cfg.InstallDiskPath(); got != tt.wantPath {
			t.Errorf("InstallDiskPath(%q) = %q, want %q", tt.disk, got, tt.wantPath)
		}
		if got := cfg.ImageTag(); got != tt.wantTag {
			t.Errorf("ImageTag(%q) = %q, want %q", tt.image, got, tt.wantTag)
		}
	}
	var nilCfg *Config
	if nilCfg.InstallDiskPath() != "" || nilCfg.ImageTag() != "" {
		t.Fatal("nil Config accessors must return empty strings")
	}
}
